@Gateway.API_HostAddress = http://localhost:5002

GET {{Gateway.API_HostAddress}}/api/rides/e277ab75-e040-4cce-835e-87a3dd8bf1f6
Accept: application/json
Authorization: Bearer 


###
POST {{Gateway.API_HostAddress}}/api/rides
Content-Type: application/json
Authorization: Bearer 


{
  "RiderId": "971e6c78-f337-4396-87b7-e93f7a5389d8"
}