@Rider.API_HostAddress = http://localhost:5053

GET {{Rider.API_HostAddress}}/api/rides/1
Accept: application/json


###
POST {{Rider.API_HostAddress}}/api/rides/
Content-Type: application/json

{
  "RiderId": "971e6c78-f337-4396-87b7-e93f7a5389d8"
}


###
PUT {{Rider.API_HostAddress}}/api/rides/assign
Content-Type: application/json

{
  "RideId": "cc51334e-1a82-4305-92f5-0f757cdfc506",
  "DriverId": "b6a7dde4-5daf-496c-b7a9-c53921f23c27"
}


###
PUT {{Rider.API_HostAddress}}/api/rides/init
Content-Type: application/json

{
  "RideId": "cc51334e-1a82-4305-92f5-0f757cdfc506"
}


###
PUT {{Rider.API_HostAddress}}/api/rides/complete
Content-Type: application/json

{
  "RideId": "cc51334e-1a82-4305-92f5-0f757cdfc506"
}
