global using System.Text;
global using System.Text.Json;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Hosting;
global using RabbitMQ.Client;
global using Microsoft.Extensions.DependencyInjection;
global using RabbitMQ.Client.Events;
global using StackExchange.Redis;
global using Polly;