global using MediatR;
global using myRideApp.Location.Domain.Models;
global using myRideApp.Location.Domain.Abstractions;
global using myRideApp.Utilities.Cache;
global using Microsoft.Extensions.DependencyInjection;
global using myRideApp.Utilities.EventBus;
global using myRideApp.Utilities.Resiliency;
global using Microsoft.EntityFrameworkCore;
global using myRideApp.Drivers.Infrastructure;
